// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// CreateWorkOKCode is the HTTP code returned for type CreateWorkOK
const CreateWorkOKCode int = 200

/*CreateWorkOK ok

swagger:response createWorkOK
*/
type CreateWorkOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Work `json:"body,omitempty"`
}

// NewCreateWorkOK creates CreateWorkOK with default headers values
func NewCreateWorkOK() *CreateWorkOK {

	return &CreateWorkOK{}
}

// WithPayload adds the payload to the create work o k response
func (o *CreateWorkOK) WithPayload(payload *v1.Work) *CreateWorkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create work o k response
func (o *CreateWorkOK) SetPayload(payload *v1.Work) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateWorkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
