// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// CreateClassOKCode is the HTTP code returned for type CreateClassOK
const CreateClassOKCode int = 200

/*CreateClassOK ok

swagger:response createClassOK
*/
type CreateClassOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Class `json:"body,omitempty"`
}

// NewCreateClassOK creates CreateClassOK with default headers values
func NewCreateClassOK() *CreateClassOK {

	return &CreateClassOK{}
}

// WithPayload adds the payload to the create class o k response
func (o *CreateClassOK) WithPayload(payload *v1.Class) *CreateClassOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create class o k response
func (o *CreateClassOK) SetPayload(payload *v1.Class) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateClassOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
