// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// CreateMoveDataOKCode is the HTTP code returned for type CreateMoveDataOK
const CreateMoveDataOKCode int = 200

/*CreateMoveDataOK ok

swagger:response createMoveDataOK
*/
type CreateMoveDataOK struct {

	/*
	  In: Body
	*/
	Payload *v1.MoveData `json:"body,omitempty"`
}

// NewCreateMoveDataOK creates CreateMoveDataOK with default headers values
func NewCreateMoveDataOK() *CreateMoveDataOK {

	return &CreateMoveDataOK{}
}

// WithPayload adds the payload to the create move data o k response
func (o *CreateMoveDataOK) WithPayload(payload *v1.MoveData) *CreateMoveDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create move data o k response
func (o *CreateMoveDataOK) SetPayload(payload *v1.MoveData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateMoveDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
