// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime/middleware"
)

// DeleteClassHandlerFunc turns a function with the right signature into a delete class handler
type DeleteClassHandlerFunc func(DeleteClassParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteClassHandlerFunc) Handle(params DeleteClassParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteClassHandler interface for that can handle valid delete class params
type DeleteClassHandler interface {
	Handle(DeleteClassParams, *v1.Principal) middleware.Responder
}

// NewDeleteClass creates a new http.Handler for the delete class operation
func NewDeleteClass(ctx *middleware.Context, handler DeleteClassHandler) *DeleteClass {
	return &DeleteClass{Context: ctx, Handler: handler}
}

/* DeleteClass swagger:route DELETE /v1/class/{id} monitor deleteClass

删除班级信息

删除班级信息

*/
type DeleteClass struct {
	Context *middleware.Context
	Handler DeleteClassHandler
}

func (o *DeleteClass) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteClassParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
