// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime/middleware"
)

// DeleteWorkSubmitHandlerFunc turns a function with the right signature into a delete work submit handler
type DeleteWorkSubmitHandlerFunc func(DeleteWorkSubmitParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteWorkSubmitHandlerFunc) Handle(params DeleteWorkSubmitParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteWorkSubmitHandler interface for that can handle valid delete work submit params
type DeleteWorkSubmitHandler interface {
	Handle(DeleteWorkSubmitParams, *v1.Principal) middleware.Responder
}

// NewDeleteWorkSubmit creates a new http.Handler for the delete work submit operation
func NewDeleteWorkSubmit(ctx *middleware.Context, handler DeleteWorkSubmitHandler) *DeleteWorkSubmit {
	return &DeleteWorkSubmit{Context: ctx, Handler: handler}
}

/* DeleteWorkSubmit swagger:route DELETE /v1/workSubmit/{id} monitor deleteWorkSubmit

删除作业提交信息

删除作业提交信息

*/
type DeleteWorkSubmit struct {
	Context *middleware.Context
	Handler DeleteWorkSubmitHandler
}

func (o *DeleteWorkSubmit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteWorkSubmitParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
