// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// DeleteMoveDataOKCode is the HTTP code returned for type DeleteMoveDataOK
const DeleteMoveDataOKCode int = 200

/*DeleteMoveDataOK A successful response.

swagger:response deleteMoveDataOK
*/
type DeleteMoveDataOK struct {

	/*
	  In: Body
	*/
	Payload *v1.MoveData `json:"body,omitempty"`
}

// NewDeleteMoveDataOK creates DeleteMoveDataOK with default headers values
func NewDeleteMoveDataOK() *DeleteMoveDataOK {

	return &DeleteMoveDataOK{}
}

// WithPayload adds the payload to the delete move data o k response
func (o *DeleteMoveDataOK) WithPayload(payload *v1.MoveData) *DeleteMoveDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete move data o k response
func (o *DeleteMoveDataOK) SetPayload(payload *v1.MoveData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMoveDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
