// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// DeleteMovePrescriptionHandlerFunc turns a function with the right signature into a delete move prescription handler
type DeleteMovePrescriptionHandlerFunc func(DeleteMovePrescriptionParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteMovePrescriptionHandlerFunc) Handle(params DeleteMovePrescriptionParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteMovePrescriptionHandler interface for that can handle valid delete move prescription params
type DeleteMovePrescriptionHandler interface {
	Handle(DeleteMovePrescriptionParams, *v1.Principal) middleware.Responder
}

// NewDeleteMovePrescription creates a new http.Handler for the delete move prescription operation
func NewDeleteMovePrescription(ctx *middleware.Context, handler DeleteMovePrescriptionHandler) *DeleteMovePrescription {
	return &DeleteMovePrescription{Context: ctx, Handler: handler}
}

/* DeleteMovePrescription swagger:route DELETE /v1/movePrescription/{id} monitor deleteMovePrescription

删除运动处方信息

删除运动处方信息

*/
type DeleteMovePrescription struct {
	Context *middleware.Context
	Handler DeleteMovePrescriptionHandler
}

func (o *DeleteMovePrescription) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteMovePrescriptionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
