// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// DeleteMovePrescriptionOKCode is the HTTP code returned for type DeleteMovePrescriptionOK
const DeleteMovePrescriptionOKCode int = 200

/*DeleteMovePrescriptionOK A successful response.

swagger:response deleteMovePrescriptionOK
*/
type DeleteMovePrescriptionOK struct {

	/*
	  In: Body
	*/
	Payload *v1.MovePrescription `json:"body,omitempty"`
}

// NewDeleteMovePrescriptionOK creates DeleteMovePrescriptionOK with default headers values
func NewDeleteMovePrescriptionOK() *DeleteMovePrescriptionOK {

	return &DeleteMovePrescriptionOK{}
}

// WithPayload adds the payload to the delete move prescription o k response
func (o *DeleteMovePrescriptionOK) WithPayload(payload *v1.MovePrescription) *DeleteMovePrescriptionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete move prescription o k response
func (o *DeleteMovePrescriptionOK) SetPayload(payload *v1.MovePrescription) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMovePrescriptionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
