// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// DeleteMoveDataHandlerFunc turns a function with the right signature into a delete move data handler
type DeleteMoveDataHandlerFunc func(DeleteMoveDataParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteMoveDataHandlerFunc) Handle(params DeleteMoveDataParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteMoveDataHandler interface for that can handle valid delete move data params
type DeleteMoveDataHandler interface {
	Handle(DeleteMoveDataParams, *v1.Principal) middleware.Responder
}

// NewDeleteMoveData creates a new http.Handler for the delete move data operation
func NewDeleteMoveData(ctx *middleware.Context, handler DeleteMoveDataHandler) *DeleteMoveData {
	return &DeleteMoveData{Context: ctx, Handler: handler}
}

/* DeleteMoveData swagger:route DELETE /v1/moveData/{id} monitor deleteMoveData

删除运动数据信息

删除运动数据信息

*/
type DeleteMoveData struct {
	Context *middleware.Context
	Handler DeleteMoveDataHandler
}

func (o *DeleteMoveData) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteMoveDataParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
