// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// DeleteWorkOKCode is the HTTP code returned for type DeleteWorkOK
const DeleteWorkOKCode int = 200

/*DeleteWorkOK A successful response.

swagger:response deleteWorkOK
*/
type DeleteWorkOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Work `json:"body,omitempty"`
}

// NewDeleteWorkOK creates DeleteWorkOK with default headers values
func NewDeleteWorkOK() *DeleteWorkOK {

	return &DeleteWorkOK{}
}

// WithPayload adds the payload to the delete work o k response
func (o *DeleteWorkOK) WithPayload(payload *v1.Work) *DeleteWorkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete work o k response
func (o *DeleteWorkOK) SetPayload(payload *v1.Work) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWorkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
