// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime"
)

// GetClassOKCode is the HTTP code returned for type GetClassOK
const GetClassOKCode int = 200

/*GetClassOK A successful response.

swagger:response getClassOK
*/
type GetClassOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Class `json:"body,omitempty"`
}

// NewGetClassOK creates GetClassOK with default headers values
func NewGetClassOK() *GetClassOK {

	return &GetClassOK{}
}

// WithPayload adds the payload to the get class o k response
func (o *GetClassOK) WithPayload(payload *v1.Class) *GetClassOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get class o k response
func (o *GetClassOK) SetPayload(payload *v1.Class) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClassOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
