// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// GetClassesOKCode is the HTTP code returned for type GetClassesOK
const GetClassesOKCode int = 200

/*GetClassesOK ok

swagger:response getClassesOK
*/
type GetClassesOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Classes `json:"body,omitempty"`
}

// NewGetClassesOK creates GetClassesOK with default headers values
func NewGetClassesOK() *GetClassesOK {

	return &GetClassesOK{}
}

// WithPayload adds the payload to the get classes o k response
func (o *GetClassesOK) WithPayload(payload *v1.Classes) *GetClassesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get classes o k response
func (o *GetClassesOK) SetPayload(payload *v1.Classes) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClassesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
