// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime/middleware"
)

// GetMoveDatasHandlerFunc turns a function with the right signature into a get move datas handler
type GetMoveDatasHandlerFunc func(GetMoveDatasParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMoveDatasHandlerFunc) Handle(params GetMoveDatasParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetMoveDatasHandler interface for that can handle valid get move datas params
type GetMoveDatasHandler interface {
	Handle(GetMoveDatasParams, *v1.Principal) middleware.Responder
}

// NewGetMoveDatas creates a new http.Handler for the get move datas operation
func NewGetMoveDatas(ctx *middleware.Context, handler GetMoveDatasHandler) *GetMoveDatas {
	return &GetMoveDatas{Context: ctx, Handler: handler}
}

/* GetMoveDatas swagger:route GET /v1/moveDatas monitor getMoveDatas

获取运动数据信息列表

获取运动数据信息列表

*/
type GetMoveDatas struct {
	Context *middleware.Context
	Handler GetMoveDatasHandler
}

func (o *GetMoveDatas) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetMoveDatasParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
