// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime/middleware"
)

// GetCaseDatasHandlerFunc turns a function with the right signature into a get case datas handler
type GetCaseDatasHandlerFunc func(GetCaseDatasParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCaseDatasHandlerFunc) Handle(params GetCaseDatasParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetCaseDatasHandler interface for that can handle valid get case datas params
type GetCaseDatasHandler interface {
	Handle(GetCaseDatasParams, *v1.Principal) middleware.Responder
}

// NewGetCaseDatas creates a new http.Handler for the get case datas operation
func NewGetCaseDatas(ctx *middleware.Context, handler GetCaseDatasHandler) *GetCaseDatas {
	return &GetCaseDatas{Context: ctx, Handler: handler}
}

/* GetCaseDatas swagger:route GET /v1/caseDatas monitor getCaseDatas

获取病例数据信息列表

获取病例数据信息列表

*/
type GetCaseDatas struct {
	Context *middleware.Context
	Handler GetCaseDatasHandler
}

func (o *GetCaseDatas) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCaseDatasParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
