// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// GetWorkSubmitHandlerFunc turns a function with the right signature into a get work submit handler
type GetWorkSubmitHandlerFunc func(GetWorkSubmitParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWorkSubmitHandlerFunc) Handle(params GetWorkSubmitParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetWorkSubmitHandler interface for that can handle valid get work submit params
type GetWorkSubmitHandler interface {
	Handle(GetWorkSubmitParams, *v1.Principal) middleware.Responder
}

// NewGetWorkSubmit creates a new http.Handler for the get work submit operation
func NewGetWorkSubmit(ctx *middleware.Context, handler GetWorkSubmitHandler) *GetWorkSubmit {
	return &GetWorkSubmit{Context: ctx, Handler: handler}
}

/* GetWorkSubmit swagger:route GET /v1/workSubmit/{id} monitor getWorkSubmit

获取作业提交信息

获取作业提交信息

*/
type GetWorkSubmit struct {
	Context *middleware.Context
	Handler GetWorkSubmitHandler
}

func (o *GetWorkSubmit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetWorkSubmitParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
