// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime/middleware"
)

// GetMeasureDetailsHandlerFunc turns a function with the right signature into a get measure details handler
type GetMeasureDetailsHandlerFunc func(GetMeasureDetailsParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMeasureDetailsHandlerFunc) Handle(params GetMeasureDetailsParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetMeasureDetailsHandler interface for that can handle valid get measure details params
type GetMeasureDetailsHandler interface {
	Handle(GetMeasureDetailsParams, *v1.Principal) middleware.Responder
}

// NewGetMeasureDetails creates a new http.Handler for the get measure details operation
func NewGetMeasureDetails(ctx *middleware.Context, handler GetMeasureDetailsHandler) *GetMeasureDetails {
	return &GetMeasureDetails{Context: ctx, Handler: handler}
}

/* GetMeasureDetails swagger:route GET /v1/measureDetails monitor getMeasureDetails

获取测评数据明细信息列表

获取测评数据明细信息列表

*/
type GetMeasureDetails struct {
	Context *middleware.Context
	Handler GetMeasureDetailsHandler
}

func (o *GetMeasureDetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetMeasureDetailsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
