// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// GetMoveDataOKCode is the HTTP code returned for type GetMoveDataOK
const GetMoveDataOKCode int = 200

/*GetMoveDataOK A successful response.

swagger:response getMoveDataOK
*/
type GetMoveDataOK struct {

	/*
	  In: Body
	*/
	Payload *v1.MoveData `json:"body,omitempty"`
}

// NewGetMoveDataOK creates GetMoveDataOK with default headers values
func NewGetMoveDataOK() *GetMoveDataOK {

	return &GetMoveDataOK{}
}

// WithPayload adds the payload to the get move data o k response
func (o *GetMoveDataOK) WithPayload(payload *v1.MoveData) *GetMoveDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get move data o k response
func (o *GetMoveDataOK) SetPayload(payload *v1.MoveData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMoveDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
