// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "gitee.com/healthy/backend/apiserver/v1"
)

// GetMovePrescriptionsOKCode is the HTTP code returned for type GetMovePrescriptionsOK
const GetMovePrescriptionsOKCode int = 200

/*GetMovePrescriptionsOK ok

swagger:response getMovePrescriptionsOK
*/
type GetMovePrescriptionsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.MovePrescriptions `json:"body,omitempty"`
}

// NewGetMovePrescriptionsOK creates GetMovePrescriptionsOK with default headers values
func NewGetMovePrescriptionsOK() *GetMovePrescriptionsOK {

	return &GetMovePrescriptionsOK{}
}

// WithPayload adds the payload to the get move prescriptions o k response
func (o *GetMovePrescriptionsOK) WithPayload(payload *v1.MovePrescriptions) *GetMovePrescriptionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get move prescriptions o k response
func (o *GetMovePrescriptionsOK) SetPayload(payload *v1.MovePrescriptions) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMovePrescriptionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
