// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "gitee.com/healthy/backend/apiserver/v1"
)

// GetWorkSubmitsOKCode is the HTTP code returned for type GetWorkSubmitsOK
const GetWorkSubmitsOKCode int = 200

/*GetWorkSubmitsOK ok

swagger:response getWorkSubmitsOK
*/
type GetWorkSubmitsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.WorkSubmits `json:"body,omitempty"`
}

// NewGetWorkSubmitsOK creates GetWorkSubmitsOK with default headers values
func NewGetWorkSubmitsOK() *GetWorkSubmitsOK {

	return &GetWorkSubmitsOK{}
}

// WithPayload adds the payload to the get work submits o k response
func (o *GetWorkSubmitsOK) WithPayload(payload *v1.WorkSubmits) *GetWorkSubmitsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get work submits o k response
func (o *GetWorkSubmitsOK) SetPayload(payload *v1.WorkSubmits) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWorkSubmitsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
