// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// GetMovePrescriptionOKCode is the HTTP code returned for type GetMovePrescriptionOK
const GetMovePrescriptionOKCode int = 200

/*GetMovePrescriptionOK A successful response.

swagger:response getMovePrescriptionOK
*/
type GetMovePrescriptionOK struct {

	/*
	  In: Body
	*/
	Payload *v1.MovePrescription `json:"body,omitempty"`
}

// NewGetMovePrescriptionOK creates GetMovePrescriptionOK with default headers values
func NewGetMovePrescriptionOK() *GetMovePrescriptionOK {

	return &GetMovePrescriptionOK{}
}

// WithPayload adds the payload to the get move prescription o k response
func (o *GetMovePrescriptionOK) WithPayload(payload *v1.MovePrescription) *GetMovePrescriptionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get move prescription o k response
func (o *GetMovePrescriptionOK) SetPayload(payload *v1.MovePrescription) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMovePrescriptionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
