// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// GetWorksHandlerFunc turns a function with the right signature into a get works handler
type GetWorksHandlerFunc func(GetWorksParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWorksHandlerFunc) Handle(params GetWorksParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetWorksHandler interface for that can handle valid get works params
type GetWorksHandler interface {
	Handle(GetWorksParams, *v1.Principal) middleware.Responder
}

// NewGetWorks creates a new http.Handler for the get works operation
func NewGetWorks(ctx *middleware.Context, handler GetWorksHandler) *GetWorks {
	return &GetWorks{Context: ctx, Handler: handler}
}

/* GetWorks swagger:route GET /v1/works monitor getWorks

获取作业信息列表

获取作业信息列表

*/
type GetWorks struct {
	Context *middleware.Context
	Handler GetWorksHandler
}

func (o *GetWorks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetWorksParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
