// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime/middleware"
)

// GetClassesHandlerFunc turns a function with the right signature into a get classes handler
type GetClassesHandlerFunc func(GetClassesParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClassesHandlerFunc) Handle(params GetClassesParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetClassesHandler interface for that can handle valid get classes params
type GetClassesHandler interface {
	Handle(GetClassesParams, *v1.Principal) middleware.Responder
}

// NewGetClasses creates a new http.Handler for the get classes operation
func NewGetClasses(ctx *middleware.Context, handler GetClassesHandler) *GetClasses {
	return &GetClasses{Context: ctx, Handler: handler}
}

/* GetClasses swagger:route GET /v1/classes monitor getClasses

获取班级信息列表

获取班级信息列表

*/
type GetClasses struct {
	Context *middleware.Context
	Handler GetClassesHandler
}

func (o *GetClasses) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetClassesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
