// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime/middleware"
)

// GetMovePrescriptionHandlerFunc turns a function with the right signature into a get move prescription handler
type GetMovePrescriptionHandlerFunc func(GetMovePrescriptionParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMovePrescriptionHandlerFunc) Handle(params GetMovePrescriptionParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetMovePrescriptionHandler interface for that can handle valid get move prescription params
type GetMovePrescriptionHandler interface {
	Handle(GetMovePrescriptionParams, *v1.Principal) middleware.Responder
}

// NewGetMovePrescription creates a new http.Handler for the get move prescription operation
func NewGetMovePrescription(ctx *middleware.Context, handler GetMovePrescriptionHandler) *GetMovePrescription {
	return &GetMovePrescription{Context: ctx, Handler: handler}
}

/* GetMovePrescription swagger:route GET /v1/movePrescription/{id} monitor getMovePrescription

获取运动处方信息

获取运动处方信息

*/
type GetMovePrescription struct {
	Context *middleware.Context
	Handler GetMovePrescriptionHandler
}

func (o *GetMovePrescription) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetMovePrescriptionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
