// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// GetCaseDataHandlerFunc turns a function with the right signature into a get case data handler
type GetCaseDataHandlerFunc func(GetCaseDataParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCaseDataHandlerFunc) Handle(params GetCaseDataParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetCaseDataHandler interface for that can handle valid get case data params
type GetCaseDataHandler interface {
	Handle(GetCaseDataParams, *v1.Principal) middleware.Responder
}

// NewGetCaseData creates a new http.Handler for the get case data operation
func NewGetCaseData(ctx *middleware.Context, handler GetCaseDataHandler) *GetCaseData {
	return &GetCaseData{Context: ctx, Handler: handler}
}

/* GetCaseData swagger:route GET /v1/caseData/{id} monitor getCaseData

获取病例数据信息

获取病例数据信息

*/
type GetCaseData struct {
	Context *middleware.Context
	Handler GetCaseDataHandler
}

func (o *GetCaseData) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCaseDataParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
