// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// GetMovePrescriptionsHandlerFunc turns a function with the right signature into a get move prescriptions handler
type GetMovePrescriptionsHandlerFunc func(GetMovePrescriptionsParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMovePrescriptionsHandlerFunc) Handle(params GetMovePrescriptionsParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetMovePrescriptionsHandler interface for that can handle valid get move prescriptions params
type GetMovePrescriptionsHandler interface {
	Handle(GetMovePrescriptionsParams, *v1.Principal) middleware.Responder
}

// NewGetMovePrescriptions creates a new http.Handler for the get move prescriptions operation
func NewGetMovePrescriptions(ctx *middleware.Context, handler GetMovePrescriptionsHandler) *GetMovePrescriptions {
	return &GetMovePrescriptions{Context: ctx, Handler: handler}
}

/* GetMovePrescriptions swagger:route GET /v1/movePrescriptions monitor getMovePrescriptions

获取运动处方信息列表

获取运动处方信息列表

*/
type GetMovePrescriptions struct {
	Context *middleware.Context
	Handler GetMovePrescriptionsHandler
}

func (o *GetMovePrescriptions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetMovePrescriptionsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
