// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime"
)

// UpdateWorkSubmitOKCode is the HTTP code returned for type UpdateWorkSubmitOK
const UpdateWorkSubmitOKCode int = 200

/*UpdateWorkSubmitOK A successful response.

swagger:response updateWorkSubmitOK
*/
type UpdateWorkSubmitOK struct {

	/*
	  In: Body
	*/
	Payload *v1.WorkSubmit `json:"body,omitempty"`
}

// NewUpdateWorkSubmitOK creates UpdateWorkSubmitOK with default headers values
func NewUpdateWorkSubmitOK() *UpdateWorkSubmitOK {

	return &UpdateWorkSubmitOK{}
}

// WithPayload adds the payload to the update work submit o k response
func (o *UpdateWorkSubmitOK) WithPayload(payload *v1.WorkSubmit) *UpdateWorkSubmitOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update work submit o k response
func (o *UpdateWorkSubmitOK) SetPayload(payload *v1.WorkSubmit) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateWorkSubmitOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
