// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// UpdateClassHandlerFunc turns a function with the right signature into a update class handler
type UpdateClassHandlerFunc func(UpdateClassParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateClassHandlerFunc) Handle(params UpdateClassParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateClassHandler interface for that can handle valid update class params
type UpdateClassHandler interface {
	Handle(UpdateClassParams, *v1.Principal) middleware.Responder
}

// NewUpdateClass creates a new http.Handler for the update class operation
func NewUpdateClass(ctx *middleware.Context, handler UpdateClassHandler) *UpdateClass {
	return &UpdateClass{Context: ctx, Handler: handler}
}

/* UpdateClass swagger:route PUT /v1/class/{id} monitor updateClass

编辑班级信息

编辑班级信息

*/
type UpdateClass struct {
	Context *middleware.Context
	Handler UpdateClassHandler
}

func (o *UpdateClass) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateClassParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
