// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime"
)

// UpdateMeasureDetailOKCode is the HTTP code returned for type UpdateMeasureDetailOK
const UpdateMeasureDetailOKCode int = 200

/*UpdateMeasureDetailOK A successful response.

swagger:response updateMeasureDetailOK
*/
type UpdateMeasureDetailOK struct {

	/*
	  In: Body
	*/
	Payload *v1.MeasureDetail `json:"body,omitempty"`
}

// NewUpdateMeasureDetailOK creates UpdateMeasureDetailOK with default headers values
func NewUpdateMeasureDetailOK() *UpdateMeasureDetailOK {

	return &UpdateMeasureDetailOK{}
}

// WithPayload adds the payload to the update measure detail o k response
func (o *UpdateMeasureDetailOK) WithPayload(payload *v1.MeasureDetail) *UpdateMeasureDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update measure detail o k response
func (o *UpdateMeasureDetailOK) SetPayload(payload *v1.MeasureDetail) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateMeasureDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
