// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime"
)

// UpdateClassOKCode is the HTTP code returned for type UpdateClassOK
const UpdateClassOKCode int = 200

/*UpdateClassOK A successful response.

swagger:response updateClassOK
*/
type UpdateClassOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Class `json:"body,omitempty"`
}

// NewUpdateClassOK creates UpdateClassOK with default headers values
func NewUpdateClassOK() *UpdateClassOK {

	return &UpdateClassOK{}
}

// WithPayload adds the payload to the update class o k response
func (o *UpdateClassOK) WithPayload(payload *v1.Class) *UpdateClassOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update class o k response
func (o *UpdateClassOK) SetPayload(payload *v1.Class) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateClassOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
