// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// UpdateMoveDataHandlerFunc turns a function with the right signature into a update move data handler
type UpdateMoveDataHandlerFunc func(UpdateMoveDataParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateMoveDataHandlerFunc) Handle(params UpdateMoveDataParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateMoveDataHandler interface for that can handle valid update move data params
type UpdateMoveDataHandler interface {
	Handle(UpdateMoveDataParams, *v1.Principal) middleware.Responder
}

// NewUpdateMoveData creates a new http.Handler for the update move data operation
func NewUpdateMoveData(ctx *middleware.Context, handler UpdateMoveDataHandler) *UpdateMoveData {
	return &UpdateMoveData{Context: ctx, Handler: handler}
}

/* UpdateMoveData swagger:route PUT /v1/moveData/{id} monitor updateMoveData

编辑运动数据信息

编辑运动数据信息

*/
type UpdateMoveData struct {
	Context *middleware.Context
	Handler UpdateMoveDataHandler
}

func (o *UpdateMoveData) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateMoveDataParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
