// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// UpdateMovePrescriptionHandlerFunc turns a function with the right signature into a update move prescription handler
type UpdateMovePrescriptionHandlerFunc func(UpdateMovePrescriptionParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateMovePrescriptionHandlerFunc) Handle(params UpdateMovePrescriptionParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateMovePrescriptionHandler interface for that can handle valid update move prescription params
type UpdateMovePrescriptionHandler interface {
	Handle(UpdateMovePrescriptionParams, *v1.Principal) middleware.Responder
}

// NewUpdateMovePrescription creates a new http.Handler for the update move prescription operation
func NewUpdateMovePrescription(ctx *middleware.Context, handler UpdateMovePrescriptionHandler) *UpdateMovePrescription {
	return &UpdateMovePrescription{Context: ctx, Handler: handler}
}

/* UpdateMovePrescription swagger:route PUT /v1/movePrescription/{id} monitor updateMovePrescription

编辑运动处方信息

编辑运动处方信息

*/
type UpdateMovePrescription struct {
	Context *middleware.Context
	Handler UpdateMovePrescriptionHandler
}

func (o *UpdateMovePrescription) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateMovePrescriptionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
