// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime/middleware"
)

// UpdateWorkHandlerFunc turns a function with the right signature into a update work handler
type UpdateWorkHandlerFunc func(UpdateWorkParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateWorkHandlerFunc) Handle(params UpdateWorkParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateWorkHandler interface for that can handle valid update work params
type UpdateWorkHandler interface {
	Handle(UpdateWorkParams, *v1.Principal) middleware.Responder
}

// NewUpdateWork creates a new http.Handler for the update work operation
func NewUpdateWork(ctx *middleware.Context, handler UpdateWorkHandler) *UpdateWork {
	return &UpdateWork{Context: ctx, Handler: handler}
}

/* UpdateWork swagger:route PUT /v1/work/{id} monitor updateWork

编辑作业信息

编辑作业信息

*/
type UpdateWork struct {
	Context *middleware.Context
	Handler UpdateWorkHandler
}

func (o *UpdateWork) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateWorkParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
