// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// UpdateMeasureDetailHandlerFunc turns a function with the right signature into a update measure detail handler
type UpdateMeasureDetailHandlerFunc func(UpdateMeasureDetailParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateMeasureDetailHandlerFunc) Handle(params UpdateMeasureDetailParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateMeasureDetailHandler interface for that can handle valid update measure detail params
type UpdateMeasureDetailHandler interface {
	Handle(UpdateMeasureDetailParams, *v1.Principal) middleware.Responder
}

// NewUpdateMeasureDetail creates a new http.Handler for the update measure detail operation
func NewUpdateMeasureDetail(ctx *middleware.Context, handler UpdateMeasureDetailHandler) *UpdateMeasureDetail {
	return &UpdateMeasureDetail{Context: ctx, Handler: handler}
}

/* UpdateMeasureDetail swagger:route PUT /v1/measureDetail/{id} monitor updateMeasureDetail

编辑测评数据明细信息

编辑测评数据明细信息

*/
type UpdateMeasureDetail struct {
	Context *middleware.Context
	Handler UpdateMeasureDetailHandler
}

func (o *UpdateMeasureDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateMeasureDetailParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
