// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime"
)

// UpdateMovePrescriptionOKCode is the HTTP code returned for type UpdateMovePrescriptionOK
const UpdateMovePrescriptionOKCode int = 200

/*UpdateMovePrescriptionOK A successful response.

swagger:response updateMovePrescriptionOK
*/
type UpdateMovePrescriptionOK struct {

	/*
	  In: Body
	*/
	Payload *v1.MovePrescription `json:"body,omitempty"`
}

// NewUpdateMovePrescriptionOK creates UpdateMovePrescriptionOK with default headers values
func NewUpdateMovePrescriptionOK() *UpdateMovePrescriptionOK {

	return &UpdateMovePrescriptionOK{}
}

// WithPayload adds the payload to the update move prescription o k response
func (o *UpdateMovePrescriptionOK) WithPayload(payload *v1.MovePrescription) *UpdateMovePrescriptionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update move prescription o k response
func (o *UpdateMovePrescriptionOK) SetPayload(payload *v1.MovePrescription) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateMovePrescriptionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
