// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime"
)

// UpdateMoveDataOKCode is the HTTP code returned for type UpdateMoveDataOK
const UpdateMoveDataOKCode int = 200

/*UpdateMoveDataOK A successful response.

swagger:response updateMoveDataOK
*/
type UpdateMoveDataOK struct {

	/*
	  In: Body
	*/
	Payload *v1.MoveData `json:"body,omitempty"`
}

// NewUpdateMoveDataOK creates UpdateMoveDataOK with default headers values
func NewUpdateMoveDataOK() *UpdateMoveDataOK {

	return &UpdateMoveDataOK{}
}

// WithPayload adds the payload to the update move data o k response
func (o *UpdateMoveDataOK) WithPayload(payload *v1.MoveData) *UpdateMoveDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update move data o k response
func (o *UpdateMoveDataOK) SetPayload(payload *v1.MoveData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateMoveDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
