// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime/middleware"
)

// DeletePersonalHandlerFunc turns a function with the right signature into a delete personal handler
type DeletePersonalHandlerFunc func(DeletePersonalParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePersonalHandlerFunc) Handle(params DeletePersonalParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeletePersonalHandler interface for that can handle valid delete personal params
type DeletePersonalHandler interface {
	Handle(DeletePersonalParams, *v1.Principal) middleware.Responder
}

// NewDeletePersonal creates a new http.Handler for the delete personal operation
func NewDeletePersonal(ctx *middleware.Context, handler DeletePersonalHandler) *DeletePersonal {
	return &DeletePersonal{Context: ctx, Handler: handler}
}

/* DeletePersonal swagger:route DELETE /v1/personal/{id} user deletePersonal

删除个人基础信息

删除个人基础信息

*/
type DeletePersonal struct {
	Context *middleware.Context
	Handler DeletePersonalHandler
}

func (o *DeletePersonal) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeletePersonalParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
