// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime"
)

// DeletePersonalOKCode is the HTTP code returned for type DeletePersonalOK
const DeletePersonalOKCode int = 200

/*DeletePersonalOK A successful response.

swagger:response deletePersonalOK
*/
type DeletePersonalOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Personal `json:"body,omitempty"`
}

// NewDeletePersonalOK creates DeletePersonalOK with default headers values
func NewDeletePersonalOK() *DeletePersonalOK {

	return &DeletePersonalOK{}
}

// WithPayload adds the payload to the delete personal o k response
func (o *DeletePersonalOK) WithPayload(payload *v1.Personal) *DeletePersonalOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete personal o k response
func (o *DeletePersonalOK) SetPayload(payload *v1.Personal) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePersonalOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
