// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime/middleware"
)

// GetPersonalsHandlerFunc turns a function with the right signature into a get personals handler
type GetPersonalsHandlerFunc func(GetPersonalsParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPersonalsHandlerFunc) Handle(params GetPersonalsParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetPersonalsHandler interface for that can handle valid get personals params
type GetPersonalsHandler interface {
	Handle(GetPersonalsParams, *v1.Principal) middleware.Responder
}

// NewGetPersonals creates a new http.Handler for the get personals operation
func NewGetPersonals(ctx *middleware.Context, handler GetPersonalsHandler) *GetPersonals {
	return &GetPersonals{Context: ctx, Handler: handler}
}

/* GetPersonals swagger:route GET /v1/personals user getPersonals

获取个人基础信息列表

获取个人基础信息列表

*/
type GetPersonals struct {
	Context *middleware.Context
	Handler GetPersonalsHandler
}

func (o *GetPersonals) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPersonalsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
