// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ModifyUserPasswordOKCode is the HTTP code returned for type ModifyUserPasswordOK
const ModifyUserPasswordOKCode int = 200

/*ModifyUserPasswordOK ok

swagger:response modifyUserPasswordOK
*/
type ModifyUserPasswordOK struct {
}

// NewModifyUserPasswordOK creates ModifyUserPasswordOK with default headers values
func NewModifyUserPasswordOK() *ModifyUserPasswordOK {

	return &ModifyUserPasswordOK{}
}

// WriteResponse to the client
func (o *ModifyUserPasswordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
