// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/healthy_backend/apiserver/v1"
)

// ModifyUserPasswordHandlerFunc turns a function with the right signature into a modify user password handler
type ModifyUserPasswordHandlerFunc func(ModifyUserPasswordParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ModifyUserPasswordHandlerFunc) Handle(params ModifyUserPasswordParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// ModifyUserPasswordHandler interface for that can handle valid modify user password params
type ModifyUserPasswordHandler interface {
	Handle(ModifyUserPasswordParams, *v1.Principal) middleware.Responder
}

// NewModifyUserPassword creates a new http.Handler for the modify user password operation
func NewModifyUserPassword(ctx *middleware.Context, handler ModifyUserPasswordHandler) *ModifyUserPassword {
	return &ModifyUserPassword{Context: ctx, Handler: handler}
}

/* ModifyUserPassword swagger:route PATCH /v1/user user modifyUserPassword

修改密码

修改密码

*/
type ModifyUserPassword struct {
	Context *middleware.Context
	Handler ModifyUserPasswordHandler
}

func (o *ModifyUserPassword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewModifyUserPasswordParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
