// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	v1 "gitee.com/healthy/backend/apiserver/v1"
	"github.com/go-openapi/runtime/middleware"
)

// UpdatePersonalHandlerFunc turns a function with the right signature into a update personal handler
type UpdatePersonalHandlerFunc func(UpdatePersonalParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdatePersonalHandlerFunc) Handle(params UpdatePersonalParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdatePersonalHandler interface for that can handle valid update personal params
type UpdatePersonalHandler interface {
	Handle(UpdatePersonalParams, *v1.Principal) middleware.Responder
}

// NewUpdatePersonal creates a new http.Handler for the update personal operation
func NewUpdatePersonal(ctx *middleware.Context, handler UpdatePersonalHandler) *UpdatePersonal {
	return &UpdatePersonal{Context: ctx, Handler: handler}
}

/* UpdatePersonal swagger:route PUT /v1/personal/{id} user updatePersonal

编辑个人基础信息

编辑个人基础信息

*/
type UpdatePersonal struct {
	Context *middleware.Context
	Handler UpdatePersonalHandler
}

func (o *UpdatePersonal) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdatePersonalParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
