// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Work 作业提交信息
//
// swagger:model Work
type Work struct {

	// 答案
	Answer string `json:"answer"`

	// 作业内容
	Content string `json:"content"`

	// 作业对象
	Creater string `json:"creater"`

	// id
	// Read Only: true
	ID string `json:"id"`

	// 接收对象
	Receive string `json:"receive"`
}

// Validate validates this work
func (m *Work) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this work based on the context it is used
func (m *Work) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Work) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Work) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Work) UnmarshalBinary(b []byte) error {
	var res Work
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
