// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: case_data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"id"`
	Userid string `protobuf:"bytes,2,opt,name=userid,proto3" json:"userid" bson:"userid"`
}

func (x *CaseData) Reset() {
	*x = CaseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_case_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseData) ProtoMessage() {}

func (x *CaseData) ProtoReflect() protoreflect.Message {
	mi := &file_case_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseData.ProtoReflect.Descriptor instead.
func (*CaseData) Descriptor() ([]byte, []int) {
	return file_case_data_proto_rawDescGZIP(), []int{0}
}

func (x *CaseData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CaseData) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

type CreateCaseDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *CaseData `protobuf:"bytes,1,opt,name=data,proto3" json:"data" bson:"data"`
}

func (x *CreateCaseDataRequest) Reset() {
	*x = CreateCaseDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_case_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCaseDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCaseDataRequest) ProtoMessage() {}

func (x *CreateCaseDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_case_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCaseDataRequest.ProtoReflect.Descriptor instead.
func (*CreateCaseDataRequest) Descriptor() ([]byte, []int) {
	return file_case_data_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCaseDataRequest) GetData() *CaseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCaseDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"id"`
}

func (x *GetCaseDataRequest) Reset() {
	*x = GetCaseDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_case_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaseDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaseDataRequest) ProtoMessage() {}

func (x *GetCaseDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_case_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaseDataRequest.ProtoReflect.Descriptor instead.
func (*GetCaseDataRequest) Descriptor() ([]byte, []int) {
	return file_case_data_proto_rawDescGZIP(), []int{2}
}

func (x *GetCaseDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateCaseDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"id"`
	Data *CaseData `protobuf:"bytes,2,opt,name=data,proto3" json:"data" bson:"data"`
}

func (x *UpdateCaseDataRequest) Reset() {
	*x = UpdateCaseDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_case_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCaseDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCaseDataRequest) ProtoMessage() {}

func (x *UpdateCaseDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_case_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCaseDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateCaseDataRequest) Descriptor() ([]byte, []int) {
	return file_case_data_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCaseDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCaseDataRequest) GetData() *CaseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteCaseDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"id"`
}

func (x *DeleteCaseDataRequest) Reset() {
	*x = DeleteCaseDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_case_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCaseDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCaseDataRequest) ProtoMessage() {}

func (x *DeleteCaseDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_case_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCaseDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteCaseDataRequest) Descriptor() ([]byte, []int) {
	return file_case_data_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCaseDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCaseDatasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query" bson:"query"`
	Skip  int64  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip" bson:"skip"`
	Limit int64  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit" bson:"limit"`
}

func (x *GetCaseDatasRequest) Reset() {
	*x = GetCaseDatasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_case_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaseDatasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaseDatasRequest) ProtoMessage() {}

func (x *GetCaseDatasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_case_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaseDatasRequest.ProtoReflect.Descriptor instead.
func (*GetCaseDatasRequest) Descriptor() ([]byte, []int) {
	return file_case_data_proto_rawDescGZIP(), []int{5}
}

func (x *GetCaseDatasRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetCaseDatasRequest) GetSkip() int64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetCaseDatasRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetCaseDatasReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount int64       `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count" bson:"total_count"`
	Items      []*CaseData `protobuf:"bytes,2,rep,name=items,proto3" json:"items" bson:"items"`
}

func (x *GetCaseDatasReply) Reset() {
	*x = GetCaseDatasReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_case_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaseDatasReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaseDatasReply) ProtoMessage() {}

func (x *GetCaseDatasReply) ProtoReflect() protoreflect.Message {
	mi := &file_case_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaseDatasReply.ProtoReflect.Descriptor instead.
func (*GetCaseDatasReply) Descriptor() ([]byte, []int) {
	return file_case_data_proto_rawDescGZIP(), []int{6}
}

func (x *GetCaseDatasReply) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetCaseDatasReply) GetItems() []*CaseData {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_case_data_proto protoreflect.FileDescriptor

var file_case_data_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x32, 0x0a, 0x08, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x15, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6b, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x58, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x61, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32,
	0xc1, 0x02, 0x0a, 0x0f, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x73,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00,
	0x12, 0x35, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x73,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61,
	0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x00, 0x12, 0x40, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x73, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79,
	0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_case_data_proto_rawDescOnce sync.Once
	file_case_data_proto_rawDescData = file_case_data_proto_rawDesc
)

func file_case_data_proto_rawDescGZIP() []byte {
	file_case_data_proto_rawDescOnce.Do(func() {
		file_case_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_case_data_proto_rawDescData)
	})
	return file_case_data_proto_rawDescData
}

var file_case_data_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_case_data_proto_goTypes = []interface{}{
	(*CaseData)(nil),              // 0: pb.CaseData
	(*CreateCaseDataRequest)(nil), // 1: pb.CreateCaseDataRequest
	(*GetCaseDataRequest)(nil),    // 2: pb.GetCaseDataRequest
	(*UpdateCaseDataRequest)(nil), // 3: pb.UpdateCaseDataRequest
	(*DeleteCaseDataRequest)(nil), // 4: pb.DeleteCaseDataRequest
	(*GetCaseDatasRequest)(nil),   // 5: pb.GetCaseDatasRequest
	(*GetCaseDatasReply)(nil),     // 6: pb.GetCaseDatasReply
}
var file_case_data_proto_depIdxs = []int32{
	0, // 0: pb.CreateCaseDataRequest.data:type_name -> pb.CaseData
	0, // 1: pb.UpdateCaseDataRequest.data:type_name -> pb.CaseData
	0, // 2: pb.GetCaseDatasReply.items:type_name -> pb.CaseData
	1, // 3: pb.CaseDataManager.CreateCaseData:input_type -> pb.CreateCaseDataRequest
	2, // 4: pb.CaseDataManager.GetCaseData:input_type -> pb.GetCaseDataRequest
	3, // 5: pb.CaseDataManager.UpdateCaseData:input_type -> pb.UpdateCaseDataRequest
	4, // 6: pb.CaseDataManager.DeleteCaseData:input_type -> pb.DeleteCaseDataRequest
	5, // 7: pb.CaseDataManager.GetCaseDatas:input_type -> pb.GetCaseDatasRequest
	0, // 8: pb.CaseDataManager.CreateCaseData:output_type -> pb.CaseData
	0, // 9: pb.CaseDataManager.GetCaseData:output_type -> pb.CaseData
	0, // 10: pb.CaseDataManager.UpdateCaseData:output_type -> pb.CaseData
	0, // 11: pb.CaseDataManager.DeleteCaseData:output_type -> pb.CaseData
	6, // 12: pb.CaseDataManager.GetCaseDatas:output_type -> pb.GetCaseDatasReply
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_case_data_proto_init() }
func file_case_data_proto_init() {
	if File_case_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_case_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_case_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCaseDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_case_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaseDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_case_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCaseDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_case_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCaseDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_case_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaseDatasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_case_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaseDatasReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_case_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_case_data_proto_goTypes,
		DependencyIndexes: file_case_data_proto_depIdxs,
		MessageInfos:      file_case_data_proto_msgTypes,
	}.Build()
	File_case_data_proto = out.File
	file_case_data_proto_rawDesc = nil
	file_case_data_proto_goTypes = nil
	file_case_data_proto_depIdxs = nil
}
