// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: work_submit.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkSubmit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"id"`
	Studentid string `protobuf:"bytes,2,opt,name=studentid,proto3" json:"studentid" bson:"studentid"`
	Taskid    string `protobuf:"bytes,3,opt,name=taskid,proto3" json:"taskid" bson:"taskid"`
	Content   string `protobuf:"bytes,4,opt,name=content,proto3" json:"content" bson:"content"`
}

func (x *WorkSubmit) Reset() {
	*x = WorkSubmit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_submit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkSubmit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkSubmit) ProtoMessage() {}

func (x *WorkSubmit) ProtoReflect() protoreflect.Message {
	mi := &file_work_submit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkSubmit.ProtoReflect.Descriptor instead.
func (*WorkSubmit) Descriptor() ([]byte, []int) {
	return file_work_submit_proto_rawDescGZIP(), []int{0}
}

func (x *WorkSubmit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkSubmit) GetStudentid() string {
	if x != nil {
		return x.Studentid
	}
	return ""
}

func (x *WorkSubmit) GetTaskid() string {
	if x != nil {
		return x.Taskid
	}
	return ""
}

func (x *WorkSubmit) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateWorkSubmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *WorkSubmit `protobuf:"bytes,1,opt,name=data,proto3" json:"data" bson:"data"`
}

func (x *CreateWorkSubmitRequest) Reset() {
	*x = CreateWorkSubmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_submit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkSubmitRequest) ProtoMessage() {}

func (x *CreateWorkSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_submit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkSubmitRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkSubmitRequest) Descriptor() ([]byte, []int) {
	return file_work_submit_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkSubmitRequest) GetData() *WorkSubmit {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetWorkSubmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"id"`
}

func (x *GetWorkSubmitRequest) Reset() {
	*x = GetWorkSubmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_submit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkSubmitRequest) ProtoMessage() {}

func (x *GetWorkSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_submit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkSubmitRequest.ProtoReflect.Descriptor instead.
func (*GetWorkSubmitRequest) Descriptor() ([]byte, []int) {
	return file_work_submit_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkSubmitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateWorkSubmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"id"`
	Data *WorkSubmit `protobuf:"bytes,2,opt,name=data,proto3" json:"data" bson:"data"`
}

func (x *UpdateWorkSubmitRequest) Reset() {
	*x = UpdateWorkSubmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_submit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWorkSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkSubmitRequest) ProtoMessage() {}

func (x *UpdateWorkSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_submit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkSubmitRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkSubmitRequest) Descriptor() ([]byte, []int) {
	return file_work_submit_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWorkSubmitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkSubmitRequest) GetData() *WorkSubmit {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteWorkSubmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"id"`
}

func (x *DeleteWorkSubmitRequest) Reset() {
	*x = DeleteWorkSubmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_submit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWorkSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkSubmitRequest) ProtoMessage() {}

func (x *DeleteWorkSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_submit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkSubmitRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkSubmitRequest) Descriptor() ([]byte, []int) {
	return file_work_submit_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteWorkSubmitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWorkSubmitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query" bson:"query"`
	Skip  int64  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip" bson:"skip"`
	Limit int64  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit" bson:"limit"`
}

func (x *GetWorkSubmitsRequest) Reset() {
	*x = GetWorkSubmitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_submit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkSubmitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkSubmitsRequest) ProtoMessage() {}

func (x *GetWorkSubmitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_submit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkSubmitsRequest.ProtoReflect.Descriptor instead.
func (*GetWorkSubmitsRequest) Descriptor() ([]byte, []int) {
	return file_work_submit_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkSubmitsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetWorkSubmitsRequest) GetSkip() int64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetWorkSubmitsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetWorkSubmitsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount int64         `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count" bson:"total_count"`
	Items      []*WorkSubmit `protobuf:"bytes,2,rep,name=items,proto3" json:"items" bson:"items"`
}

func (x *GetWorkSubmitsReply) Reset() {
	*x = GetWorkSubmitsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_submit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkSubmitsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkSubmitsReply) ProtoMessage() {}

func (x *GetWorkSubmitsReply) ProtoReflect() protoreflect.Message {
	mi := &file_work_submit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkSubmitsReply.ProtoReflect.Descriptor instead.
func (*GetWorkSubmitsReply) Descriptor() ([]byte, []int) {
	return file_work_submit_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorkSubmitsReply) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetWorkSubmitsReply) GetItems() []*WorkSubmit {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_work_submit_proto protoreflect.FileDescriptor

var file_work_submit_proto_rawDesc = []byte{
	0x0a, 0x11, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x6c, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57,
	0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x17,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x17, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72,
	0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22,
	0x5c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0xe1, 0x02,
	0x0a, 0x11, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72,
	0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72,
	0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72,
	0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72,
	0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x57,
	0x6f, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x2f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_work_submit_proto_rawDescOnce sync.Once
	file_work_submit_proto_rawDescData = file_work_submit_proto_rawDesc
)

func file_work_submit_proto_rawDescGZIP() []byte {
	file_work_submit_proto_rawDescOnce.Do(func() {
		file_work_submit_proto_rawDescData = protoimpl.X.CompressGZIP(file_work_submit_proto_rawDescData)
	})
	return file_work_submit_proto_rawDescData
}

var file_work_submit_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_work_submit_proto_goTypes = []interface{}{
	(*WorkSubmit)(nil),              // 0: pb.WorkSubmit
	(*CreateWorkSubmitRequest)(nil), // 1: pb.CreateWorkSubmitRequest
	(*GetWorkSubmitRequest)(nil),    // 2: pb.GetWorkSubmitRequest
	(*UpdateWorkSubmitRequest)(nil), // 3: pb.UpdateWorkSubmitRequest
	(*DeleteWorkSubmitRequest)(nil), // 4: pb.DeleteWorkSubmitRequest
	(*GetWorkSubmitsRequest)(nil),   // 5: pb.GetWorkSubmitsRequest
	(*GetWorkSubmitsReply)(nil),     // 6: pb.GetWorkSubmitsReply
}
var file_work_submit_proto_depIdxs = []int32{
	0, // 0: pb.CreateWorkSubmitRequest.data:type_name -> pb.WorkSubmit
	0, // 1: pb.UpdateWorkSubmitRequest.data:type_name -> pb.WorkSubmit
	0, // 2: pb.GetWorkSubmitsReply.items:type_name -> pb.WorkSubmit
	1, // 3: pb.WorkSubmitManager.CreateWorkSubmit:input_type -> pb.CreateWorkSubmitRequest
	2, // 4: pb.WorkSubmitManager.GetWorkSubmit:input_type -> pb.GetWorkSubmitRequest
	3, // 5: pb.WorkSubmitManager.UpdateWorkSubmit:input_type -> pb.UpdateWorkSubmitRequest
	4, // 6: pb.WorkSubmitManager.DeleteWorkSubmit:input_type -> pb.DeleteWorkSubmitRequest
	5, // 7: pb.WorkSubmitManager.GetWorkSubmits:input_type -> pb.GetWorkSubmitsRequest
	0, // 8: pb.WorkSubmitManager.CreateWorkSubmit:output_type -> pb.WorkSubmit
	0, // 9: pb.WorkSubmitManager.GetWorkSubmit:output_type -> pb.WorkSubmit
	0, // 10: pb.WorkSubmitManager.UpdateWorkSubmit:output_type -> pb.WorkSubmit
	0, // 11: pb.WorkSubmitManager.DeleteWorkSubmit:output_type -> pb.WorkSubmit
	6, // 12: pb.WorkSubmitManager.GetWorkSubmits:output_type -> pb.GetWorkSubmitsReply
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_work_submit_proto_init() }
func file_work_submit_proto_init() {
	if File_work_submit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_work_submit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkSubmit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_submit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkSubmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_submit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkSubmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_submit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWorkSubmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_submit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWorkSubmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_submit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkSubmitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_submit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkSubmitsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_work_submit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_work_submit_proto_goTypes,
		DependencyIndexes: file_work_submit_proto_depIdxs,
		MessageInfos:      file_work_submit_proto_msgTypes,
	}.Build()
	File_work_submit_proto = out.File
	file_work_submit_proto_rawDesc = nil
	file_work_submit_proto_goTypes = nil
	file_work_submit_proto_depIdxs = nil
}
